### PR TITLE
Bug fix: fix definition of d2h in imaging notebooks

### PR DESCRIPTION
**Pull request by JBeechert**
I found a bug in the simulation imaging notebooks which only appeared when imaging source-only 511 keV, 26Al, and point sources. Because all of the recent testing has been done with the source+Ling files, I didn't notice it until today.

During the internal COSIpy working group review, `d2h = n_time_bins` (where `n_time_bins = analysis1.dataset.binned_data.shape[0]`), was changed to `d2h = analysis1.dataset.times.n_time_bins`. These aren’t the same in the source-only simulations and the bug produces an error further down in the notebook:
> ValueError                                Traceback (most recent call last)
> Cell In [31], line 2
>       1 print('ebin: ',ebin)
> ----> 2 dataset = analysis1.dataset.binned_data[:,ebin,:,:].reshape(d2h,
>       3                                                             analysis1.dataset.phis.n_phi_bins*analysis1.dataset.fisbels.n_fisbel_bins)[:,nonzero_idx]
> 
> ValueError: cannot reshape array of size 36685800 into shape (2210,34350)

I fixed this by redefining d2h as `d2h = analysis1.dataset.binned_data.shape[0]`.

To eliminate confusion about these different ways of expressing the number of time bins, I also removed text at the beginning of the notebooks which incorrectly calls out `analysis1.dataset.times.n_time_bins` as the number of time bins. @tsiegert thinks that this object is an intra-time-bin number used to weight the response within one DeltaT; it isn't relevant here.

I also made a few typo fixes and edited a print statement in `response_dc1.py` to say "Reading response." instead of always saying "Reading complete continuum response."

### CODE REVIEW

**Comment by ckarwin** [comment]
Nice catch, Jackie. The changes look good.

One point to clarify:
"To eliminate confusion about these different ways of expressing the number of time bins, I also removed text at the beginning of the notebooks which incorrectly calls out analysis1.dataset.times.n_time_bins as the number of time bins. @tsiegert thinks that this object is an intra-time-bin number used to weight the response within one DeltaT; it isn't relevant here."

analysis1.dataset.times.n_time_bins is just the total number of time bins, before making a sparse array, i.e. before removing bins with 0 counts:
self.n_time_bins = int(np.ceil(np.diff(minmax(self.data['TimeTags']))/self.init_time_bin_size))

Whereas analysis1.dataset.binned_data.shape[0] is the number of time bins for the sparse array. I think this also makes sense with the error, since with the Ling BG all the time bins are populated, but not for source only.

Is this in line with what you were thinking?

**Comment by tsiegert** [comment]
Yeah, I think this makes sense. Test, if the notebook is running when you change it back, then we can merge again.

**Comment by ckarwin** [comment]
I'm testing the notebook now. 

@JBeechert, one comment: The markdown says: "Number of time bins (should be the first dimension of the response)"
I'm not sure what you mean by this. The number of time bins, in this case, is given by the first dimension of the data. The response doesn't have time. I would just remove "(should be the first dimension of the response)". Or let me know if I'm missing something here.

**Comment by JBeechert** [comment]
> Whereas analysis1.dataset.binned_data.shape[0] is the number of time bins for the sparse array. I think this also makes sense with the error, since with the Ling BG all the time bins are populated, but not for source only.
> 
> Is this in line with what you were thinking?

@ckarwin yes, thanks for correcting my explanation. 

> I would just remove "(should be the first dimension of the response)".

This was a holdover from earlier versions of the notebook. Can't remember why it was there anymore. I removed it from the notebooks in the latest commit.

**Comment by ckarwin** [comment]
Thank for the clarification, and making those additional changes, @JBeechert 

I tested RL-DataChallenge-Point_Sources-10XFlux-Ling.ipynb with the normal input sims. It runs fine, and gives the same results as last time I tested it. I think this PR is ok to be merged now.

@tsiegert If there are no other issues, can you merge this PR?

**Comment by ckarwin** [comment]
Thomas has approved. I'll merge the PR.

**Pull request merged**
